# editor completions
"$schema" = "https://starship.rs/config-schema.json"

# append newlines to command outputs
add_newline = true

# custom format
format = """
$shlvl\
$singularity\
$kubernetes\
$directory\
$vcsh\
$fossil_branch\
$git_branch\
$git_commit\
$git_state\
$git_metrics\
$git_status\
$hg_branch\
$pijul_channel\
$docker_context\
$package\
$c\
$cmake\
$cobol\
$daml\
$dart\
$deno\
$dotnet\
$elixir\
$elm\
$erlang\
$fennel\
$golang\
$guix_shell\
$haskell\
$haxe\
$helm\
$java\
$julia\
$kotlin\
$gradle\
$lua\
$nim\
$nodejs\
$ocaml\
$opa\
$perl\
$php\
$pulumi\
$purescript\
$python\
$raku\
$rlang\
$red\
$ruby\
$rust\
$scala\
$swift\
$terraform\
$vlang\
$vagrant\
$zig\
$buf\
$nix_shell\
$conda\
$meson\
$spack\
$memory_usage\
$env_var\
$crystal\
$custom\
$sudo\
$cmd_duration\
$line_break\
$jobs\
$status\
$character"""

# prompt chars
[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"
vimcmd_symbol = "[❮](bold green)"
vimcmd_replace_one_symbol = "[❮](bold yellow)"
vimcmd_replace_symbol = "[❮](bold yellow)"
vimcmd_visual_symbol = "[❮](bold cyan)"

[directory]
style = "#87FF5F bold"
truncation_length = 6

[git_branch]
symbol = "[「󰊢 ](blue)"
style = "bright-blue"
format = '[$symbol$branch(:$remote_branch) ]($style)'

[git_status]
ahead = "⇡${count}"
behind = "⇣${count}"
conflicted = '$count'
deleted = " "
diverged = '↑$ahead_count↓$behind_count'
modified = "󱇬 "
renamed = " "
staged = "󰝒 "
stashed = "󰬲 "
untracked = ""
style = "yellow"
format = "([$all_status$ahead_behind]($style)[」](blue))"

[cmd_duration]
style = "white"
